### ISSUE TITLE
works for koa?

### ISSUE THREAD

**Issue by ziyaaktas** [sebhildebrandt/http-graceful-shutdown#20] opened 2022-12-01 23:20 UTC
I tried it with koa@2.13.4, but I get an error TypeError: server.close is not a function.

**Comment by sebhildebrandt** [comment] 2022-12-02 04:54
@ziyaaktas as I am using it for several projects with koa, I assume that this works. Can you give a little more context of your code (creating the server, calling the `gracefulShutdown` function, ...) and please also your `koa`, `gracefulShutdown` and `node.js` version.

Thank you in advance

**Comment by sebhildebrandt** [comment] 2022-12-05 09:57
@ziyaaktas closing it for now, cannot reproduce it without further input.

**Closed as completed by sebhildebrandt** 2022-12-05 09:57 UTC

**Comment by bkspace** [comment] 2022-12-14 16:33
Just ran into this issue aswell:

![image](https://user-images.githubusercontent.com/1695350/207653482-f51ad0ae-881f-4e1d-8981-c55c5f5dd302.png)

Happy to dig in further :)

**Comment by sebhildebrandt** [comment] 2022-12-14 22:19
@bkspace @ziyaaktas can you try the following:

```
git clone https://github.com/sebhildebrandt/http-graceful-shutdown.git
cd http-graceful-shutdown/examples
npm install debug koa

// if you want to use debugging
export DEBUG=http-graceful-shutdown

// then run theminimal koa app
node koa-simple-server.js

// when pressing CTRL-C you should the get some output
// In my case it is 

  http-graceful-shutdown received shut down signal SIGINT +0ms
  http-graceful-shutdown shutdown signal - SIGINT +1ms
  http-graceful-shutdown shutting down +0ms
  http-graceful-shutdown Destroy Connections : close +0ms
  http-graceful-shutdown Connections destroyed : 1 +0ms
  http-graceful-shutdown Connection Counter    : 3 +0ms
  http-graceful-shutdown Secure Connections destroyed : 0 +0ms
  http-graceful-shutdown Secure Connection Counter    : 0 +0ms
  http-graceful-shutdown Close http server +0ms
  http-graceful-shutdown waitForReadyToShutDown... 120 +1ms
  http-graceful-shutdown All connections closed. Continue to shutting down +0ms
  http-graceful-shutdown Do onShutdown now +0ms
  http-graceful-shutdown executing finally() +0ms
```

If this runs without any error, we should basically be fine but if it still does not run with your application, can you share a minimal version of how you setup your server?

Regards

**Comment by twobitfool** [comment] 2023-01-25 18:43
@ziyaaktas - I had a similar issue. 

When you call `gracefulShutdown` make sure that you pass in the http `server` and not the koa `app`...

```js
  const app = new Koa()
  const server = app.listen()

  // Correct 👍
  gracefulShutdown(server)

  // ⛔️ Incorrect - TypeError: server.close is not a function
  gracefulShutdown(app)
```
